management:
  endpoints:
    web:
      exposure:
        include: "*"  # rabbitmq, ex) http://localhost:9265/actuator/bus-refresh (POST)
#        include: ['env', 'refresh'] # endpoint, ex) http://localhost:9265/actuator/refresh
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
